# Workflow name
name: packer validate 
on:
  # Triggers the workflow on push events but only for the main branch
  pull_request:
    types: [opened, reopened]
    branches:
      - devel
    paths:
      - 'images/*.pkr.hcl'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  list-packer-files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'devel'
      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls images/*.pkr.hcl | jq -R -s -c 'split("\n")[:-1]')"
  
  validate:
    needs: list-packer-files
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            packer-file: ${{ fromJson(needs.list-packer-files.outputs.matrix) }}
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'devel'
  
    - name: Install python requirements
      run: pip install -r requirements.txt 
      
    - name: Install packer
      run: sudo apt-get update; sudo apt-get install packer
      
    - name: Validate image with packer
      id: packer-validate
      run: packer validate ${{ matrix.packer-file }}

# # Would rather use this but not working with ansible and haven't investigated
#     - name: Validate ${{ matrix.packer-file }}
#       uses: hashicorp/packer-github-actions@master
#       with:
#         command: validate
#         target: ${{ matrix.packer-file }}
